-- This query calculates the total revenue generated by each organizer from ticket fees of their events.
-- It performs a multi-table join between 'organizers', 'events', and 'tickets' tables.
-- The result is grouped by the organizer's name, summing up the ticket fees for each organizer.
-- Only organizers with a total revenue greater than 0 are included.
-- The result is ordered by total revenue in descending order to show the highest revenue first.

SELECT o.name AS organizer_name, SUM(t.fee) AS total_revenue
FROM organizers o
JOIN events e ON o.organizer_id = e.organizer_id
JOIN tickets t ON e.event_id = t.event_id
GROUP BY o.name
HAVING SUM(t.fee) > 0
ORDER BY total_revenue DESC;



